services:
  - type: web
    name: collaborative-ide-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: RAPID_API_KEY
        sync: false
    buildFilter:
      paths:
      - server.js
      - package.json